[package]
authors    =["Thor Kampefner <thorck@pm.me>"]
description="""a"""
edition    ="2021"
name       ="cgtb"
repository ="https://github.com/thor314/cgtb"
version    ="0.1.0"

[dependencies]
anyhow   ="1.0"
cute = "0.3.0"
log       ="0.4" 
thiserror="1.0"
env_logger = "0.11"
dotenvy = "0.15"


[dev-dependencies]
rstest    ="0.18"         # testing convenience proc-macros
